# Generated by Django 2.1.15 on 2021-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alpha_numer',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='alphabet',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='numeric',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
    ]
